var products = [
{
        image:"61H0F7UucpL._SY355_.jpg",
        title: "black and white nike gloves",
        price: "40.00",
        sizes: ["small", "medium", "large"],
        description:"black and white Nike gloves with extra grip",
        colors:["Black", "white"],
        materials: ["30% plastic", "30% rubber", "40% cotton"], 
        brand: "Nike",
        categories:["men", "youth", "gloves"],
        product_id: "a;woeruoi"
    },
    {
        image:"adidas dog cleats.jpg",
        title: "Adidas dog cleats",
        price: "140.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"cleats with a pitbull on it",
        colors:["brown", "white",],
        materials: ["30% plastic", "30% rubber", "40% cotton"], 
        brand: "Adidas",
        categories:["men", "shoes"],
        product_id: "o9u234r98"
    }, 
    {
        image:"usa-football-cleats.jpg",
        title: "USA under armor cleats",
        price: "140.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"this is a USA under armor cleats",
        colors:["red", "white", "blue"],
        materials: ["30% plastic"," 30% rubber", "40% cotton"], 
        brand: "Under Armor",
        categories:["men","youth","shoes"],
        product_id: "jijyjiyjij"
        
    }, 
    {
        image:"black addias cleats.jpg",
        title: "Black adidas cleats",
        price: "140.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"this is a USA under armor cleats",
        colors:["red", "white", "blue"],
        materials: ["30% plastic", "30% rubber", "40% cotton"], 
        brand: "Adidas",
        categories:["men","shoes"],
        product_id: "mbgbjgbjbjgh"
    }, 
    {
        image:"old football cleats.jpg",
        title: "Old fashioned football cleats",
        price:"200.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"back in the day when they had old lether",
        colors:["red", "white", "blue"],
        materials: ["30% plastic", "30% rubber"," 40% cotton"], 
        brand: "Under Armor",
        categories:["men","shoes"],
        product_id: "ehrehrhyrgh"
    }, 
    {
        image:"wilson football.jpg",
        title: "Wilson football",
        price: "140.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"this is a USA under armor cleats",
        colors:["red", "white", "blue"],
        materials: ["30% plastic", "30% rubber"," 40% cotton"], 
        brand: "Under Armor",
        categories:["men","footballs"],
        product_id: "jtigjtgjgitgjij"
    }, 
    {
        image:"red stripe under armor.jpg",
        title: "red stripe cleats",
        price: "140.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"this is a USA under armor cleats",
        colors:["red", "white", "blue"],
        materials: ["30% plastic", "30% rubber", "40% cotton"], 
        brand: "Under Armor",
        categories:["men", "youth","shoes",],
        product_id: "a;woeryoi"
    }, 
    {
        image:"NFL football.jpg",
        title: "NFL football",
        price: "140.00",
        sizes: ["7", "8", "9", "10", "11",],
        description:"this is a USA under armor cleats",
        colors:["red", "white", "blue"],
        materials: ["30% plastic", "30% rubber", "40% cotton"], 
        brand: "Under Armor",
        categories:["men","footballs"],
        product_id: "a;woeruog"
    }, 
    {
        image:"Blue white vapor cleats.jpg",
        title: "Blue white vapor cleats",
        price:" 140.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"",
        colors:["red", "white", "blue"],
        materials: ["30% plastic"," 30% rubber"," 40% cotton"], 
        brand: "Nike",
        categories:["men", "youth","shoes",],
        product_id: "a;woeruom"
    }, 
    {
        image:"black battle gloves.png",
        title: "Black Battle Gloves",
        price:" 140.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"",
        colors:["red", "white", "blue"],
        materials: ["30% plastic", "30% rubber", "40% cotton"], 
        brand: "Battle",
        categories:["men", "youth","gloves"],
        product_id: "a;woeruos"
    }, 
    {
        image:"CN cleats.jpg",
        title: "CN Cleats",
        price:" 140.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"CN brand",
        colors:["red", "white", "blue"],
        materials: ["30% plastic", "30% rubber"," 40% cotton"], 
        brand: "CN",
        categories:["men", "youth","shoes"],
        product_id: "a;woeruei"
    }, 
    {
        image:"footballcleats.jpg",
        title: "Gold and white Nike Cleats",
        price: "140.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"Gold and white",
        colors:["red", "white", "blue"],
        materials: ["30% plastic", "30% rubber"," 40% cotton"], 
        brand: "Nike",
        categories:["men", "youth","shoes"],
        product_id: "a;woerupo"
    }, 
    {
        image:"gold white cleat.jpg",
        title: "Black, White and Gold",
        price: "140.00",
        sizes: ["7", "8", "9", "10", "11",],
        description:"this is a USA under armor cleats",
        colors:["white", "gold",],
        materials: ["30% plastic"," 30% rubber"," 40% cotton",], 
        brand: "Nike",
        categories:["men", "youth","shoes",],
        product_id: "a;wokpruoi"
    }, 
    {
        image:"gold and white .jpg",
        title: "Gold and white battle Gloves",
        price: "50",
        sizes: ["7", "8", "9", "10", "11",],
        description:"gold",
        colors:["red", "white", "blue",],
        materials: ["30% plastic"," 30% rubber"," 40% cotton",], 
        brand: "Battle",
        categories:["men", "youth","gloves",],
        product_id: "a;woeruji"
    }, 
    {
        image:"line men black cleats.jpg",
        title: "Line men Black cleats",
        price: " 140.00",
        sizes: ["7", "8", "9", "10", "11",],
        description:"line men ",
        colors:["black",],
        materials: ["30% plastic"," 30% rubber"," 40% cotton",], 
        brand: "Under Armor",
        categories:["men", "youth","shoes",],
        product_id: "a;woeruui"
    }, 
    {
        image:"X1046_1005_right2.jpg",
        title: "black Vapor Cleats",
        price:  "140.00",
        sizes: ["7", "8", "9", "10", "11",],
        description:"Black Nike",
        colors:["Black",],
        materials: ["30% plastic"," 30% rubber", "40% cotton",], 
        brand: "Nike",
        categories:["men", "youth","shoes"],
        product_id: "a;woerueei"
    }, 
    {
        image:"black and yellow cleats.jpg",
        title: "Black and yellow cleats",
        price:  " 140.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"this is a USA under armor cleats",
        colors:["yellow", "Black"],
        materials: ["30% plastic", "30% rubber"," 40% cotton"], 
        brand: "Under Armor",
        categories:["men", "youth","shoes",],
        product_id: "a;werruoi"
    }, 
    {
        image:"footballcleats2.jpg",
        title: "Money cleats",
        price:  " 140.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"money",
        colors: ["white", "green"],
        materials: ["30% plastic", "30% rubber"," 40% cotton"], 
        brand: "Adidas",
        categories:["men","shoes"],
        product_id: "a;woeyuooi"
    }, 
    {
        image:"gold under armor.jpg",
        title: "gold under armor",
        price:  "140.00",
        sizes: ["7", "8", "9", "10", "11"],
        description:"gold",
        colors:["Black", "gold"],
        materials: ["30% plastic"," 30% rubber", "40% cotton"], 
        brand: "Under Armor",
        categories:["men", "youth","shoes",],
        product_id: "aggtgteruoi"
    }, 
    {
        image:"army.jpg",
        title: "army cleats",
        price:  "140.00",
        sizes: ["7", "8", "9", "10", "11",],
        description:"army",
        colors:["tan", "Black", "green",],
        materials: ["30% plastic", "30% rubber", "40% cotton"],
        categories:["men","shoes",],
        product_id: "a;wortiypoykg5uoi"
    },  
        


];